name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Jest
        run: npm test

      #- name: Buildar imagem Docker
      #  run: docker build -t minha-imagem .

      # Aqui você pode adicionar etapas para deploy, como SSH, Heroku, etc.
      - name: Finalizando
        run: echo "Build completo!"
